os: osx
env:
  global:
    - CC_TEST_REPORTER_ID=5f027b55abd445130817bc8bec2ba805352ef1a3a994012d9b967495fcd64b02
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.4
  - 2.5.0
  - 2.5.1
  - ruby-head
before_install: 
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - rvm get head
  - gem install bundler -v 1.16.1
before_script: 
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
matrix:
  allow_failures:
    - rvm: ruby-head
