os: 
  - osx
env:
  global:
    - CC_TEST_REPORTER_ID=5f027b55abd445130817bc8bec2ba805352ef1a3a994012d9b967495fcd64b02
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.4
  - 2.5.0
  - 2.5.1
  - ruby-head
before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gpg --import rvm.gpg && rvm get head; fi- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && rvm get head; fi
  - gem install bundler
before_script: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: 
  - bundle install && bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
matrix:
  allow_failures:
    - rvm: ruby-head
