env:
  global:
    - CC_TEST_REPORTER_ID=5f027b55abd445130817bc8bec2ba805352ef1a3a994012d9b967495fcd64b02
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.0
before_install: 
  - gem install bundler -v 1.16.2
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
after-install:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
